import { useState, useEffect } from 'react'
import { Box, Paper, Typography, IconButton, Tooltip, Chip } from '@mui/material'
import { ContentCopy, Check } from '@mui/icons-material'
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter'
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism'
import { generateContract } from '../utils/contractGenerator'
import type { ContractTemplate, DeploymentParams } from '../types'
import { useTranslation } from 'react-i18next'
import { useChainId } from 'wagmi'
interface CodeViewerProps {
  template: ContractTemplate
  params: Record<string, any>
}
const CodeViewer = ({ template, params }: CodeViewerProps) => {
  const { t } = useTranslation()
  const chainId = useChainId()
  const [code, setCode] = useState<string>('')
  const [copied, setCopied] = useState(false)
  useEffect(() => {
    try {
      const deploymentParams: DeploymentParams = {
        template: template.id,
        params,
        chainId,
        premiumFeatures: params.premiumFeatures || [],
      }
      const generatedCode = generateContract(deploymentParams)
      setCode(generatedCode)
    } catch (error) {
      console.error('Error generating contract:', error)
      setCode('// Error generating contract code')
    }
  }, [template, params, chainId])
  const handleCopy = () => {
    navigator.clipboard.writeText(code)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }
  return (
    <Paper
      elevation={0}
      sx={{
        p: 3,
        height: '100%',
        background: 'linear-gradient(135deg, rgba(26, 32, 46, 0.9) 0%, rgba(17, 24, 39, 0.95) 100%)',
        backdropFilter: 'blur(10px)',
        border: '1px solid',
        borderColor: 'rgba(92, 107, 192, 0.2)',
        borderRadius: 2,
        position: 'relative',
      }}
    >
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
          <Typography variant="h6" sx={{ fontWeight: 600 }}>
            {t('codeViewer.title')}
          </Typography>
          <Chip
            label="Generated by ContractForge.io"
            size="small"
            sx={{
              background: 'linear-gradient(135deg, #5C6BC0 0%, #7E57C2 100%)',
              color: 'white',
              fontWeight: 500,
              fontSize: '0.75rem',
              height: 24,
              '& .MuiChip-label': {
                px: 2,
              },
            }}
          />
        </Box>
        <Tooltip title={copied ? t('codeViewer.copied') : t('codeViewer.copy')}>
          <IconButton onClick={handleCopy} size="small">
            {copied ? <Check /> : <ContentCopy />}
          </IconButton>
        </Tooltip>
      </Box>
      <Box
        sx={{
          backgroundColor: '#1e1e1e',
          borderRadius: 1,
          overflow: 'hidden',
          position: 'relative',
          '&::before': {
            content: '"Generated by ContractForge.io"',
            position: 'absolute',
            top: 8,
            right: 16,
            fontSize: '0.75rem',
            color: 'rgba(255, 255, 255, 0.3)',
            fontFamily: 'monospace',
            zIndex: 1,
          },
        }}
      >
        <Box
          sx={{
            maxHeight: '600px',
            overflow: 'auto',
            '&::-webkit-scrollbar': {
              width: '8px',
            },
            '&::-webkit-scrollbar-track': {
              background: 'rgba(255, 255, 255, 0.1)',
            },
            '&::-webkit-scrollbar-thumb': {
              background: 'rgba(92, 107, 192, 0.5)',
              borderRadius: '4px',
              '&:hover': {
                background: 'rgba(92, 107, 192, 0.7)',
              },
            },
          }}
        >
          <SyntaxHighlighter
            language="solidity"
            style={vscDarkPlus}
            customStyle={{
              margin: 0,
              padding: '1rem',
              background: 'transparent',
              fontSize: '0.875rem',
              lineHeight: '1.5',
            }}
            showLineNumbers
          >
            {code}
          </SyntaxHighlighter>
        </Box>
      </Box>
      <Box sx={{ mt: 2, display: 'flex', justifyContent: 'center' }}>
        <Typography
          variant="caption"
          sx={{
            color: 'text.secondary',
            textAlign: 'center',
            '& a': {
              color: '#5C6BC0',
              textDecoration: 'none',
              '&:hover': {
                textDecoration: 'underline',
              },
            },
          }}
        >
          Smart contracts audited and secured by{' '}
          <a href="https://openzeppelin.com/contracts/" target="_blank" rel="noopener noreferrer">
            OpenZeppelin
          </a>
        </Typography>
      </Box>
    </Paper>
  )
}
export default CodeViewer